name: Development CI

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: rm package-lock.json
    - run: cp .env.example.development .env
    - name: build project
      run: CI=false yarn build
    - name: Copy the project to development directory
      run: cp -r -f /home/dev/actions-runner/_work/dashboard-wooden/dashboard-wooden/build /home/dev/woodendoor/development


