// Aside Menu Icon
import agent from './3rd-party-agents-icon.svg';
import brokers from './brokers-icon.svg';
import calendar from './calendar-icon.svg';
import car from './car-icon.svg';
import dashboard from './dashboard-icon.svg';
import employees from './employees-icon.svg';
import inquiries from './inquiries-icon.svg';
import leads from './leads-icon.svg';
import owners from './owners-icon.svg';
import properties from './properties-icon.svg';
import yachts from './yachts-icon.svg';
import menuIcon from './tableMenuIcon.svg';
import tableListProduct from './listTableProduct.png';
import inputSearch from './inputSearch.svg';
import selectIcon from './selecticon.svg';
import randomImage from './graph2.png';
import filledCrossIcon from './filledCrossIcon.svg';
import dropDownIcon from './dropdownIcon.svg'
import uploadfileIcon from './uploadfileIcon.png';
import profileIcon from './profile.svg'
import customDatepickerIcon from './customDatepickerIcon.svg';
import nopicture from './no-pictures.png';
import featuredProperty from './featuredProperty.svg';
import discount from './discount.svg'
import slide from './slide1.jpg'
import uploadImg from './uploadImg.png'

export { agent, slide, nopicture, uploadImg ,  featuredProperty, discount, customDatepickerIcon, uploadfileIcon, profileIcon, dropDownIcon, selectIcon, randomImage, filledCrossIcon, inputSearch, brokers, calendar, car, dashboard, employees, inquiries, leads, owners, properties, yachts, menuIcon, tableListProduct }